### ISSUE TITLE
Panic on deletion of gene

### ISSUE THREAD

**Issue by Byter09** [Fr4ctlize/OxiNEAT#3]
Hello again!

I hope I'm not being annoying haha. I got a panic when running one of my rather big datasets.

If it helps, the only thing I changed to previous runs was to set
```rust
node_deletion_mutation_chance: 0.01,
gene_deletion_mutation_chance: 0.02,
```

so I assume raising these even further will only make the problem happen more often. In my case it happened on generation 682 with a population size of 5000. The species count at that time was 1507.

If I had to guess, somewhere in there a check whether deletion is okay is not done correctly. Please note that the source file in which this happened is a local one, but the branch I'm using is behind by only a single commit which didn't touch this part. I have a very hard time reproducing this problem. I hope this stack backtrace can help you.
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/btr/Projects/clion/oxineat/oxineat-nn/src/genomics.rs:868:56
stack backtrace:
   0:     0x558f4a7ec8ec - std::backtrace_rs::backtrace::libunwind::trace::hd3a6cb8e32f9fc43
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x558f4a7ec8ec - std::backtrace_rs::backtrace::trace_unsynchronized::h6dcceebcd6a9f2ab
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558f4a7ec8ec - std::sys_common::backtrace::_print_fmt::h4eacf4e9ad977499
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x558f4a7ec8ec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e42c22572a7e7b4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x558f4a80eccc - core::fmt::write::h072b578a8e90aa54
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/fmt/mod.rs:1150:17
   5:     0x558f4a7e9d65 - std::io::Write::write_fmt::hc32d3cabefff1d24
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/io/mod.rs:1667:15
   6:     0x558f4a7ee4b0 - std::sys_common::backtrace::_print::h058b85b6efc15780
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x558f4a7ee4b0 - std::sys_common::backtrace::print::hdb7de10b704104b4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x558f4a7ee4b0 - std::panicking::default_hook::{{closure}}::h5451997d203bda2f
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:210:50
   9:     0x558f4a7ee067 - std::panicking::default_hook::h419b121e68f746a2
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:227:9
  10:     0x558f4a7eeb64 - std::panicking::rust_panic_with_hook::h32c44b1364c1c247
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:624:17
  11:     0x558f4a7ee612 - std::panicking::begin_panic_handler::{{closure}}::he2e5f48fb16982d1
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:519:13
  12:     0x558f4a7ecd94 - std::sys_common::backtrace::__rust_end_short_backtrace::haea54a33f9e18aba
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x558f4a7ee5a9 - rust_begin_unwind
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
  14:     0x558f4a6cb601 - core::panicking::panic_fmt::h824e0febbdf5e655
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
  15:     0x558f4a6cb54d - core::panicking::panic::h36a242770663c3a8
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:50:5
  16:     0x558f4a783a0e - oxineat_nn::genomics::NNGenome::remove_gene_unchecked::hb63eca7632f98ef1
  17:     0x558f4a7ac262 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h71d3d1326513bcd7
  18:     0x558f4a783bc5 - oxineat_nn::genomics::NNGenome::remove_node_unchecked::hb6166b75800a75e0
  19:     0x558f4a783563 - oxineat_nn::genomics::NNGenome::mutate_delete_node::hf843c3586b77abd6
  20:     0x558f4a784957 - oxineat_nn::genomics::NNGenome::mate::hc5dc67dd5c34ca5e
  21:     0x558f4a77f5ba - <oxineat_nn::genomics::NNGenome as oxineat::genome::Genome>::mate::hf79eae8749077132
  22:     0x558f4a70c408 - oxineat::populations::offspring_factory::OffspringFactory<C,H,G>::generate_offspring::hd4fdbfcfeb66d27b
  23:     0x558f4a6e9174 - oxineat::populations::Population<C,H,G>::evolve::h7bbdfa80812b02fb
  24:     0x558f4a6fb91f - premarket::main::h9b9f58dbf33e5b49
  25:     0x558f4a6e7ed3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc585b0edfad2d2bb
  26:     0x558f4a6f0e2d - std::rt::lang_start::{{closure}}::h938ac48e100daf90
  27:     0x558f4a7ef16a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h97e9d5f21cbee92f
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:259:13
  28:     0x558f4a7ef16a - std::panicking::try::do_call::hdfecd950eba8f698
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  29:     0x558f4a7ef16a - std::panicking::try::h3c77c8ba3eb0735c
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  30:     0x558f4a7ef16a - std::panic::catch_unwind::h8e0d62076d8d837e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  31:     0x558f4a7ef16a - std::rt::lang_start_internal::{{closure}}::h647045b4c6a22e67
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/rt.rs:45:48
  32:     0x558f4a7ef16a - std::panicking::try::do_call::h905d96e4a757647e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  33:     0x558f4a7ef16a - std::panicking::try::hc113426beb3c908b
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  34:     0x558f4a7ef16a - std::panic::catch_unwind::h74f684ea7038ea12
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  35:     0x558f4a7ef16a - std::rt::lang_start_internal::h5ba185919d396c97
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/rt.rs:45:20
  36:     0x558f4a6fecb2 - main
  37:     0x7fef78935b25 - __libc_start_main
  38:     0x558f4a6cbdde - _start
  39:                0x0 - <unknown>
```

**Comment by Fr4ctlize** [comment]
I had my doubts about the full soundness of those methods when I implemented them... I feel like there's some weird corner case. Unfortunately, that backtrace isn't particularly helpful, but you are correct in that the panic occurs at a point where checks _should_ have been made. I'm not entirely sure how best to approach this.

**Comment by Byter09** [comment]
I mean, "fire-and-forget" delete could be a solution right? You simply delete something and if it does not exist in the `HashMap` nothing happens. Though, this isn't solving the problem of this probably being some logic error, which I sadly can't help with. I will dig deeper should this happen more frequent with the raised node/gene-deletion chances.

My second run is at 679 generations already, so I'll see if it happens again.

**Comment by Fr4ctlize** [comment]
I suspect I may have identified the error: if the node being removed has a recursive connection, it may be trying to remove the same gene twice. I'm going to try to get a fix and push it asap.

**Comment by Byter09** [comment]
Amazing :D Thank you!

**Comment by Fr4ctlize** [comment]
OK, the fix should be fairly branch-predictor friendly, so performance shouldn't change too much (especially since this should be a rare mutation anyways). Let me know if it happens again, but I think that should be it.
