### ISSUE TITLE
Panic when adding a gene after mating

### ISSUE THREAD

**Issue by Byter09** [Fr4ctlize/OxiNEAT#4]
Hello... again :D

This is using your latest commit (again, with minor changes to make it multithreaded for my purposes, which have no impact on any of the logic). I remember running into this problem days ago already but just shrugged it off and restarted. This time however it happened in generation 1647 with a population size of 2500 and an average gene count of 114. Which.. hurts a bit so far into the process haha.

This time I got no clue what went wrong here. I hope you appreciate these reports and don't find it annoying hahaha.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DuplicateGeneID(5993, Some((10, 10)))', /home/btr/Projects/clion/oxineat/oxineat-nn/src/genomics.r
s:658:14
stack backtrace:
   0:     0x563390231dcc - std::backtrace_rs::backtrace::libunwind::trace::hd3a6cb8e32f9fc43
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x563390231dcc - std::backtrace_rs::backtrace::trace_unsynchronized::h6dcceebcd6a9f2ab
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563390231dcc - std::sys_common::backtrace::_print_fmt::h4eacf4e9ad977499
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x563390231dcc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e42c22572a7e7b4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5633902541ac - core::fmt::write::h072b578a8e90aa54
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/fmt/mod.rs:1150:17
   5:     0x56339022f245 - std::io::Write::write_fmt::hc32d3cabefff1d24
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/io/mod.rs:1667:15
   6:     0x563390233990 - std::sys_common::backtrace::_print::h058b85b6efc15780
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x563390233990 - std::sys_common::backtrace::print::hdb7de10b704104b4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x563390233990 - std::panicking::default_hook::{{closure}}::h5451997d203bda2f
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:210:50
   9:     0x563390233547 - std::panicking::default_hook::h419b121e68f746a2
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:227:9
  10:     0x563390234044 - std::panicking::rust_panic_with_hook::h32c44b1364c1c247
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:624:17
  11:     0x563390233b20 - std::panicking::begin_panic_handler::{{closure}}::he2e5f48fb16982d1
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:521:13
  12:     0x563390232274 - std::sys_common::backtrace::__rust_end_short_backtrace::haea54a33f9e18aba
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x563390233a89 - rust_begin_unwind
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
  14:     0x563390110611 - core::panicking::panic_fmt::h824e0febbdf5e655
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
  15:     0x563390110703 - core::result::unwrap_failed::hcb2100a3c7d7df74
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:1617:5
  16:     0x5633901c74d4 - oxineat_nn::genomics::NNGenome::mutate_add_gene::h3e4af99256dffd2d
  17:     0x5633901c9d08 - oxineat_nn::genomics::NNGenome::mate::hc8ffe2ab3130326e
  18:     0x5633901c45ca - <oxineat_nn::genomics::NNGenome as oxineat::genome::Genome>::mate::hb2146f0fec688bcf
  19:     0x563390151418 - oxineat::populations::offspring_factory::OffspringFactory<C,H,G>::generate_offspring::h998e1927b50ed57a
  20:     0x56339012e1c4 - oxineat::populations::Population<C,H,G>::evolve::h0781b3a35e2e6ad4
  21:     0x56339014096f - premarket::main::hfcc314df2576ec30
  22:     0x56339012cf23 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6eec62a7c3537265
  23:     0x563390135e7d - std::rt::lang_start::{{closure}}::h582fc388472ea9eb
  24:     0x56339023464a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h97e9d5f21cbee92f
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:259:13
  25:     0x56339023464a - std::panicking::try::do_call::hdfecd950eba8f698
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  26:     0x56339023464a - std::panicking::try::h3c77c8ba3eb0735c
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  27:     0x56339023464a - std::panic::catch_unwind::h8e0d62076d8d837e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  28:     0x56339023464a - std::rt::lang_start_internal::{{closure}}::h647045b4c6a22e67
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/rt.rs:45:48
  29:     0x56339023464a - std::panicking::try::do_call::h905d96e4a757647e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  30:     0x56339023464a - std::panicking::try::hc113426beb3c908b
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  31:     0x56339023464a - std::panic::catch_unwind::h74f684ea7038ea12
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  32:     0x56339023464a - std::rt::lang_start_internal::h5ba185919d396c97
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/rt.rs:45:20
  33:     0x563390143d02 - main
  34:     0x7f05449d2b25 - __libc_start_main
  35:     0x563390110dee - _start
  36:                0x0 - <unknown>
```

Other than the occasional crash, it's working wonderfully so far, training for my data set just takes ages so when it suddenly panics its really unfortunate.

Thanks again for the great library and how responsive you are to issues!

**Comment by Fr4ctlize** [comment]
That happened because the gene addition mutation procedure tried to add a recursive gene with innovation number 5993 to a genome which already had that gene. I think I've identified the error that causes the bug, will push soon.
